CREATE TABLE USERS(
    id SERIAL PRIMARY KEY,
    username varchar(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
);


